<a href="https://colab.research.google.com/github/johnreyes96/modeling-and-simulation/blob/master/src/main/python/classes/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programación y NumPy

En la primera parte de este notebook seguiremos explorando algunas cuestiones de programación. En la segunda parte, empezaremos a trabajar con NumPy.

## 1. Programación

### 1.1 Operaciones Lógicas

En primer lugar, la operación `not` es simplemente la negación del booleano.

In [ ]:
variable_1 = True
print(not(variable_1))

variable_2 = False
print(not(variable_2))

False
True


La operación `and` nos devuelve `True` unicamente cuando ambas variables son verdaderas. Experimentar con la celda inferior y comprobar su tabla de verdad.

In [ ]:
variable_1 = True
variable_2 = True
print(variable_1 and variable_2)

True


**Ejercicio:** comprobar la tabla de verdad de la operación `or` jugando con la celda siguiente.

In [ ]:
A = False
C = False
A_or_B = A or C
print(A_or_B)

False


### 1.2 Estructuras de control - Condicionales

Los condicionales nos permiten ejecutar o no un bloque de codigo dependiendo de ciertas condiciones. En lenguaje coloquial, vendrían a ser del estilo de "Si se cumple esta condición, hace A. Si no se cumple, hace B", donde B puede ser, simplemente, no hacer nada. Veamos qué formas toman.

### 1.2.1 If

El condicional más simple es el `if`. Para mayor claridad escribiremos la condicion entre parentesis (), aunque esto no es necesario. Su estructura es 

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
```

Veamos algunos ejemplos:

In [ ]:
valor = 15
if (valor > 10):
    print('El valor es mayor que 10')

El valor es mayor que 10


Prestar atención a que la condición debe ser un booleano

In [ ]:
print(valor > 10)
print(type(valor > 10))

True
<class 'bool'>


**Nota:** para comparar variables, tenemos las operaciones menor `<`, mayor `>`, igualdad `==`, menor o igual  `<=`, y mayor o igual `>=`.

In [ ]:
print(3 == 3)
print(3 <= 4)
print(3 >= 5)

True
True
False


### 1.2.2 If, Else

A la estrucutra con `if` se le puede agregar otro bloque de codigo que se ejecute si la condición exigida NO se cumple. Esto se logra mediante la expresión `else`.

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
else:
    Si NO se cumple la condición, se ejecutan estas líneas de código
```

In [ ]:
nombre = 'Pedro'

if (nombre == 'Juan'):
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

Esta persona NO se llama Juan


En la condición - lo que está entre paréntesis - es un booleano.

In [ ]:
'Juan'=='Pedro'

False

### 1.2.3 If, Elif, Else
A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desee, mediante la expresión `elif`. El orden en que se van chequeando las condiciones depende de su posición, priemero se chequea el `if`, luego el primer `elif`, luego el segundo, y así sucesivamente.

``` python
if condicion_1:
    Si se cumple la condicion_1 , se ejecutan estas líneas de código
elif condicion_2:
    Si se cumple la condicion_2 , se ejecutan estas líneas de código
elif condicion_3:
    Si se cumple la condicion_3 , se ejecutan estas líneas de código
else:
    Si NO se cumple ninguna de las condiciones anteriores, se ejecutan líneas celdas de código
```


In [ ]:
edad = 18

if (edad < 18):
    print('Esta persona tiene menos de 18 años')
elif (edad > 18):
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

Esta persona tiene justo 18 años


**Ejercicio**: Escriba un bloque de código que, dado un número, imprima la frase "El numero es par" si el número es par o la frase "El numero es impar" si no lo es.

In [ ]:
numero = 18
# COMPLETAR
if(numero % 2 == 0):
  print("El numero es par")
else:
  print("El numero es impar")


El numero es par


### 1.3 Combinando estructuras de código

Las estructuras de loops y condicionales se pueden combinar para generar comportamientos más complejos. Supongamos que tenemos una lista de edades y nos queremos quedar con aquellas que sean mayores que 18 años. Podemos hacer lo siguiente:

In [ ]:
lista_de_edades = [4,20,15,29,11,42,10,18]
lista_mayores = []

for edad in lista_de_edades:
    if (edad > 18):
        lista_mayores.append(edad)

print(lista_mayores)

[20, 29, 42]


### 1.4 Operaciones lógicas y estructuras de control

A veces, queremos ejecutar una línea de código si se cumple más de una condición. Esto se puede lograr fácilmente usando las operaciones lógicas. Supongamos que tenemos una lista de números, y queremos seleccionar aquellos que cumplan ciertas propiedades. Por ejemplo, que son mayores o iguales que 5 y menores que 20. Podríamos hacer lo siguiente:

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5:
        if numero < 20:
            seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


Notar que los números seleccionados cumplen los requisitos que pedimos. Pero también podríamos hacerlo así:

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5 and numero < 20:
        seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


El resultado es el mismo. Si bien esta forma es más compacta, no necesariamente implica que sea mejor. Uno/a elije hacerlo de una u otra forma según lo que le parezca más claro; si ambas condiciones juntas son difíciles de leer, tal vez puedes usar la primera forma.

**Ejercicio**: Modifica el ejemplo anterior para que seleccione aquellos números **mayores** que 5 **o** impares.

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero > 5 or numero % 2 == 1:
        seleccionados.append(numero)
print(seleccionados)

[3, 1, 6, 17, 3, 89, 5, 6, 13, 25, 3, 23, 1, 15]


### Repaso

**Ejercicio 1**: ¿Qué pasa si sumás, restás, multiplicás o divides booleanos?

In [ ]:
print(True + True + True)
print(True * False)
# COMPLETAR

3
0


**Ejercicio 2**: Hacer una estructur `if/else` que compare dos variables numéricas `A` y `B` y que decida cuál es mayor e imprima en pantalla "A es mayor que B" o "B es mayor que A" . 

In [ ]:
A = 3
B = 4
# COMPLETAR

**Ejercicio 3**: Dada la siguiente lista de numeros:

In [ ]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]

Escribir una rutina que calcule la suma de los números **pares menores que 5** en esta lista. **Para tener en cuenta:** 
* Hay muchas formas de hacerlo, si piensa en más de una, mejor.
* El resultado es 20. 
* Recuerda que puede inicializar una variable en cero, y luego ir modificándola en un loop.

In [ ]:
# COMPLETAR

**Ejercicio 4**: Dada la siguiente lista de numeros:

In [ ]:
numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1', '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
print(numeros_en_texto)



Calcule la suma de los unos (1) y los tres (3) en esta lista. Nuevamente, hay muchas formas de hacerlo. **Para tener en cuenta:** 
* El resultado es 210.


In [ ]:
# COMPLETAR

## 2. Numpy

Es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

La ventaja de Numpy frente a las listas predefinidas en Python es que el procesamiento de los arrays se realiza mucho más rápido (hasta 50 veces más) que las listas, lo cual la hace ideal para el procesamiento de vectores y matrices de grandes dimensiones.

In [ ]:
import numpy as np

Ahora nuestro ambiente de trabajo sabe que si ponemos algo del estilo `np.` significa que esa funcionalidad la debe buscar en NumPy.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas y, de hecho, se pueden crear a partir de ellas.

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. Recordemos que sumarle un número a toda la lista no estaba permitido

In [ ]:
lista + 1

TypeError: ignored

¡Pero ahora con los arreglos sí!

In [ ]:
arreglo = arreglo + 1

Esto simplifica mucho hacer cuéntas. Pero no es sólo sumar, también muchas otras operaciones:

In [ ]:
print(arreglo - 5)
print(arreglo - 2)
print(arreglo*4)
print(arreglo**2)

[-4 -3 -2 -1  0  1]
[-1  0  1  2  3  4]
[ 4  8 12 16 20 24]
[ 1  4  9 16 25 36]


Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso de una lista?

### 2.1 Creación de arreglos

Si bien podemos crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo. Veamos algunas.

Una muy utilizada es `np.arange()`.

In [ ]:
np.arange(0, 5, 0.5, dtype=float)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arreglo = np.arange(3,20,2)
print(arreglo)

[ 3  5  7  9 11 13 15 17 19]


**Ejercicio:** Buscar y crear ejemplos con las siguientes funciones:
* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.
* `np.zeros` y `np.ones`

In [ ]:
arreglo = np.linspace(1,19,5)
print(arreglo)

arreglo = np.arange(1,19,4)
print(arreglo)

[ 1.   5.5 10.  14.5 19. ]
[ 1  5  9 13 17]



### 2.2 Shape de los arreglos

Los arreglos tienen muchos más propiedades que las listas. En particular, pueden tener más de un *eje* o dimensión. Veamos a qué nos referimos:

In [ ]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


Notar que tiene dos filas y cuatro columnas. Podemos descubrir esto sin imprimirlo en pantalla, sino usando la propiedad `.shape` del arreglo.

In [ ]:
print(arreglo_2d.shape)

(2, 4)


Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`? Otro ejemplo:

In [ ]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Si queremos saber cuántos elementos tiene, podemos usar `.size`

In [ ]:
print(arreglo_2d.size)

8


### 2.3 Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un montón de funciones que operan sobre los arreglos. Veamos algunos ejemplos.

In [ ]:
un_arreglo = np.array([-100,2,3,17,25,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-100
95


En el caso 2D, podemos pedir que estas funciones operen sobre todo el arreglo, o por ejes.



In [ ]:
arreglo_2d = np.arange(9)
np.random.shuffle(arreglo_2d)
arreglo_2d = arreglo_2d.reshape((3,3))
print(arreglo_2d)

[[1 6 0]
 [5 3 7]
 [8 2 4]]


In [ ]:
arreglo_2d = np.arange(9)
print(arreglo_2d)

[0 1 2 3 4 5 6 7 8]


Trata de entender la diferencia entre las siguientes instrucciones:

In [ ]:
arreglo_2d = np.arange(9)
arreglo_2d = arreglo_2d.reshape((3,3))
print(arreglo_2d)
print(arreglo_2d.max(axis = 0))
print(arreglo_2d.min(axis = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[0 3 6]


* No dijimos nada sobre indexado ni slicing. Esto se debe a que, para arreglos 1D, es similar que para la listas. Para arreglos 2D, es apenas más complicado. Para estudiarlo, jugar con la siguiente celda:

In [ ]:
arreglo_2d = np.arange(9).reshape(3,3)
print(arreglo_2d)
print(arreglo_2d[2,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]


* Podemos usar `arreglo.max()` o `np.max(arreglo)`. Esto no es válido solamente para la función `max()`, sino también para casi todas las funciones que operen sobre arreglos. 

In [ ]:
print(np.min(un_arreglo), un_arreglo.min())

-100 -100


### Repaso

**Ejercicio 1**: Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`

In [ ]:
# COMPLETAR

**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [ ]:
# COMPLETAR

**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [ ]:
# COMPLETAR

**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [ ]:
# COMPLETAR

**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [ ]:
# COMPLETAR

**Ejercicio 6:** crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0 
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```

In [ ]:
# COMPLETAR

**Extra:** ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?¿Y si queremos cambiarle el tipo de dato, por ejemplo a `int`? Googlear "numpy astype". ¿Qué pasa si usamos `astype(bool)`?